In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [32]:
dataset = pd.read_csv('C:/Users/mishr/Desktop/test_data1.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, 4].values


In [33]:
print(X)

[[    0    19 19000]
 [    0    35 20000]
 [    1    26 43000]
 ...
 [    1    50 20000]
 [    0    36 33000]
 [    1    49 36000]]


In [6]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          2
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.25,random_state=0)

In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [37]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [43]:
y_pred=classifier.predict(X_test)


In [44]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[164  10   0]
 [ 47  58   0]
 [ 13   8   0]]


In [45]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.74


In [ ]:
#this accuracy is with gender in it ....